nodes:
  - address:
      - stage1-any-sync-node1.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp1uwLB58vK61ySIeHjCZ2VBcI5USH7PjEzHzs/6nk6Un1rUK9VzsfXu3ttd1ldYP8EqYnWMNML0H7290kNsaKr32vbom7TEsZV6nz3BYIi8peTygq5KDqj3oJrwreje2tG1Ucj/VIrOxJCHzLKftLaaD9hN1J+DnXTYmGa6W7gmq/7ezWFf0WZrx7UoZeCC6kOkudvA+Eh3VI4LWi/MSnPgRgh9nnBhF8vM3I/Y6NWFIMQvD3/vPqlrJ6k3Dm/aJIvcYZ+99jDtAbdkUfkFFFi22O+SZKT2aBRsXIkJFP6FmqP+GPbe+gxRKrGmW5dnBy8FjyRsHLnnccH6LOT94HwIDAQAB
    peerId: 12D3KooWN6Wwdod3axHpfWq1anBCgYG1sZK42RpgEZEokT4KnMu7
    types:
      - tree
  - address:
      - stage1-any-sync-node2.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1D3x2RvxeQ4+fUKE/IftsAdBS5bGid7nVkUUsKaLDLcGcVe4ZjENDEKizX8IJ45villg29xJTvMG4PojWbfoBzvmwD4jEUy9XWDJPxQaPuPvN7VCrCw8fQROV3QScp0Dx/JcA7ogMolNau40+vKAo3lQi0W1VVuhSPc0c2xmccGx+u1RpCwgCmSb6SGSSvArlqv++VeIUNSL1UEmaOMvSYo+qKMIWuTBOTwDnuFB7qP0UAjQvQSvHQ/jm7DGEnQwq0d9eFnIXzn5I2pwhZGet9dPjUnr7rE33UTKaQhFSA4L2gGunm+/CGifSL50yUe1c5+cFxDNn+2XzhO1HRK+UQIDAQAB
    peerId: 12D3KooWJuqyFQ2ZgnYFNhdHAddF7DrTPP2rNueLjw5BWDJa9kqg
    types:
      - tree
  - address:
      - stage1-any-sync-node3.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAotdoSHw/rWTG8J/PirXv82qHcOHWmbdVZlTd3vHRLo2inYJLZTy8nAbJRssBEKzaFy5OjQp/FCXfq4x0z8+aQaXH7Omzyrlom0Qv1DT6HAbQC4BPljVE3M0a5WsoCYF8XTMW83oUT66ahDT++MOYg9FIbzU2Xvu2osRA69aKegid4Cc2FrZjLhC9c2+IzQdjRB0bgKYgmmuJmStMSF8+Rqp6qkkUVImRcOqyvRR/pFCBYs6RF5OmpHMpw61ieS2/nBPn8VpS7J56H2FM7Zu1oTkInn08JbdxiyQuo5kxTpIBHCQdgY6FQk/7Alyft971upC3nVxf9HptQwispkYfoQIDAQAB
    peerId: 12D3KooWCub3vY3kWmAQ5qf9TtKBHKY6Yk7F6tGb13M1sXqvcbV4
    types:
      - tree
  - address:
      - stage1-any-sync-node4.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArwxBf1IkwTB+hCfUYj3eOWHnVwTzn1X6Dn0rH5fLOjX5IzfAOt3sxj7AYEk+PupcJluwO1zyWfwr22i+RvWG2Qf7a7vR24K+HR9CZhZPsufk195Qbsrn2mBDoPKDwzXU6NS88kVaDqeZIHIqyFT6mTcGJuinaO/a4yBmbiIdpsrtdPVBnceQzAyYzHFG8xOmXFenG4pvQYrMd970MuAQbEo9pQb/GbOawtqe5W3ETeKq7uN7LcjzGojkZx7pA6BaZRBymSzidHoK9ef7eE+xzp7kiKpNDGmHIKU+CLoE/F6XnJCYCNBlJTqWXLteF4tWf+SvHVT7mCog4U9403Yz/QIDAQAB
    peerId: 12D3KooWRzT7eeiqPpkaXabqrtLEi1WmWPoUqZVRYiguUdJQz3sz
    types:
      - tree
  - address:
      - stage1-any-sync-node5.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0TOVkf79Z7KHnRc4Vnwszs8AhT+Tv50vfwGnRQgQ6IvKN2nsailw4nBOxr+YBLClK/C/J7c7BAZjNwEFQF28CYMVhr+sy3q818vPxZZevVXuSgiHisc4RAigKDd4wm0Vakg2aBkE0Go35Fxj0HARIeN2FWuf63EueO8hFkAa+01W1p198LTg7sRi/MPG2es5bTsY7CZUlR1FIEGyM5AcTj0JLq2EU6PIfwk+n1CeIgMPThHhf1xIL+xBBVUFfue4B8inyLymPJeA/Lvf4fJPY2mDf2Bz9R/25dMvPFxh3TdXD6DZzEJkNjsxihWDVMsPf/ap2hBQhO0hsNyGszXX9wIDAQAB
    peerId: 12D3KooWPkZDAzAzioUmtd2HkPeFb8mrMgkkYtfL5Es69dbhoUMT
    types:
      - tree
  - address:
      - stage1-any-sync-node6.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp8jd50ye6BoKWcWQPtL44RxesS9rtH3ThorMSweKtn0KXoUnu2b73sZ/t3H8BDNBVXUW11YSJTSzky3y9y9+IhFMWALx82S2O7I4lFxpJICqorj3/pv0Didg38qpc9A69TJmDsG/U/wifQnxszNIcWacZQ0idAS6jMJsFAZPUdljxdgzZROyXoIpf3XIGftFiwsKZVfI/AVGy7ZPoSamoB05/uB5zveHT8OSJBZVWfMkXTqZrwk5TlRF+nxQP4kxYJbQ1vSesQgIWF7dSeNyYDEsJqHFHi+rDUAoLcjFAkxquBum5QnsLq+25VSq2ZjNRYx2QBYCZoxGFL0nwx7LAQIDAQAB
    peerId: 12D3KooWF5pVsv8oaPeZj7MeAXQAbdqqrGB7AEENMnxguZtEi44V
    types:
      - tree
  - address:
      - stage1-any-sync-node7.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzqkV2ZkLYEofuQ4qtjuN5NTecsuvsv2lmnpgbQWMyxI63j4gn2tnU3eP1fIdciiqE5f5IM221RzZ2qEQZml8p1ZRhma4iaGUMARGnjBpV3C8z2rS1dj6iet8/BC7O9hc4uKS5Wz2BMv2xNYT3Yhx9h7vA6iT8goz9s6OhESW4njTcd8YuYw9bdHxcfmrKrFjAq5BFZhzS01Lbmislwm5lz8NqTgWrxJN9Ek/spbBF0Hd8SfI2VjGrI8x49X290e6GKWJr3cjc4UgX9kKkcNcXM1M+zG55nPJfaIJ+skrepOmUmsBnTkNoCGxbo/OwyOfbsmHKRtvtD9SM0sfWEBmiwIDAQAB
    peerId: 12D3KooW9xRUDQbW6bbsek45dQop9BDZBC8ATCpKxYssE8zMy2wa
    types:
      - tree
  - address:
      - stage1-any-sync-node8.anytype.io:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAseQhj+os3JpNVzxPnalXL69tFtvcZR4GjJ6Ligv+/l4yDZyUgt22T9SvFNpUaX/iolFxaUJrhf0d1z/ydvjlsrNsSxRt9h2IvFvpXG/7wi+EDrwYN9Fz8JcLq+ENSIt+US3IXAuEOyXDwv/eIbYmP/WA33x3ujJCxEy0J/feGwZoPqIGCsVdDY09Sqawb8Wh9tGI+rZHFYwQkhPdAy1EbHA5b5YTYw9pkLJB/j7ybyndkHedSNdrFIvDygGI1askFY8IHFN84k8NAM+IqRu11bt5knxIP3OMYVlc+gUGjK9Lb5VOlYLbc7CvZin9sAxhSctIxOPFZNIrTjo1XnzwxwIDAQAB
    peerId: 12D3KooWBqUE5e6BuxWDiAAvYATq36qCUvNysyDMdddUqmeCb5jG
    types:
      - tree
  - address:
      - ec2-18-159-252-150.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWKcGtB8jsW7mpB8zWMdVrPTZygnwkRoUKBd2ETmRDFa8x
    types:
      - file
  - address:
      - ec2-3-68-113-221.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWR5ishjnaTfLbwQur6ifXSQDLSroaQxWH1KHmR1YL9Srk
    types:
      - file
  - address:
      - ec2-3-75-246-136.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWAzNCQWQSdfspUCT6ea3TLvJFahEHwXndh8PQGanjHhbF
    types:
      - file
  - address:
      - ec2-3-122-177-128.eu-central-1.compute.amazonaws.com:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA159bAu9mQsZnz4maVOLEQonyjGUyErMxDsGNCcsQivyKjsOtvv6Hx/4leV2DJA45PjpN6M00Y5DDXNZW2Fe5Hyw3MpBmCZIXU0UFehk8MmElM8g9axLMfbvC9KALZk51vrQOoaaN8agbAwrT9FqAvarO8Dm8Z2Gaxev5Gdzgu2SouDad2xAJzmzR7uFVF6c3QjjRwD3dsy8zru9YIRkcPu+TnowoSf0nRSaryFBTneuBE4XcND7V8zU9jv9bctp+xCmHYJ7spX7kwm+3prVDwNOFFKeK5CEHBqiLutXeT/Bijlv8gBCRzVU+yNKpulQAk6X2aCphsh3f9E8kpEopRwIDAQAB
    peerId: 12D3KooWHyWNKYPdYeFK9eQ32UK9uqM1yTdXZT6qTTbtCowCYBAp
    types:
      - coordinator
  - address:
      - ec2-3-125-155-229.eu-central-1.compute.amazonaws.com:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAukfLFNK5LKOcoDXEINYUYxjxGHpYhWF9QIQ8bXyXgkT6hmvHwoZaZuYTY9GiQEok+pEqhJtMJ8OAx1ui86JK23aWebLV24Qh7udT7NZ7oAHw/918mJhPvszmY703jjfpkVjP7uR4wwwFdLS66vjcs2G8HICukZDA7bz03M9C9UniTAYVlpLseMwUJZX3pkSfC+HAwTBKAsqhGV3CHKwrd0w4bqYdDq113M9raNbvSxHt0LIfrWVID0M0YjqhoYenhYCiyQTJ+01dEiak69ocE4uvZ+Cy0n4pzKilMQjyN5+1NwCG2USKG0H39bVVTCB61oayQPkCD3hadxVRisCQmwIDAQAB
    peerId: 12D3KooWNPpzKPUzcf86KemKwa3ap8kBfCmPRWkBsvymGZdoBdni
    types:
      - coordinator
  - address:
      - ec2-3-65-13-48.eu-central-1.compute.amazonaws.com:443
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1JS7SocKyHavDqWySc1JaPz0oz6BFghHujp6Yh5YkVU8a7Q+M9dyJpSzk5LGT8Eri0P07tBlOoJGThMTStoT8tHRupdd2PVm1wcdYxIJ1DTj2qMOadNS1xXdHAz6FAIo/9lTuoyTpwk+mbersXukAu265SATmqbt2yaoQxvq4jI8loDoToo866CD3Ay1Le1EnnCkdZf1FUzj2+gWOy1rL99i+a2y1FoN7XHC+nYdc/FBVKNbmvKSwtjYU7PBGrsH6m8AXBETpalyCCXNTOHiy0WDt3WM+MzMJPfk1I5B501OgH1XVCXVLqwNYWyZx4jeVQjF9sLmZ8o338WD3zC58QIDAQAB
    peerId: 12D3KooWB4hmEo7YAdWzAaFpjyk4npkcwrPm2kRigsWu3MP9Xdmg
    types:
      - coordinator
