nodes:
  - peerId: 12D3KooWKnXTtbveMDUFfeSqR5dt9a4JW66tZQXG7C7PdDh3vqGu
    address:
      - 127.0.0.1:4430
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA23AWlsGaLrUxea+x6rkpy1ByqUJKdb2oS10q0urntUCivsNb7ipo1tvM2rldn6DAIrIC1nQHdlwrakNhl/j9zfX/GdACRDEuy7pVigm78QqYwSoyZn1l717HGjXKpJpa2m9Qyo6ZNGTLcej06zuOK8yUR4gudxSV5BJ2AmMvB9v4jUdCUwROSMy0e/hDa3Cx2xV33iULF/XltoeBVDoW6yYXfsok2yH3jHUV59yqQDbZO+kAj5rO8Fd/DnmGriuQZwAwdqJBH6/NtkhbA6triS/xW7f+RoyjjA3dp7TSUscHTFW0LIUaS0ZKt6amaanT7L/Jwi/0w133wTboYPG7NQIDAQAB
    types:
      - tree
  - peerId: 12D3KooWKgVN2kW8xw5Uvm2sLUnkeUNQYAvcWvF58maTzev7FjPi
    address:
      - 127.0.0.1:4431
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwQcHwXkTynIvU5PfTn9kaQEb5Zzz8eHl/uO1srbWI0hM+sIvhOq/ahYuhDlai0mAhRFQIvb6QRnWzCp3qvMH8+j8ls83BKV4hfxuS+SR/Y/LonW+WeLljiloMM5ju9tjw1iSslUK6z7d0HSLppQCCjMP+v3kKjx24qJ2T+2N1MAMbdt+S5c2P2jBUJVSvQbZ1AVuZTEzDau//+cZzV47lsODrVZ2SxW/KAAKA9xIJSIwBFyIqya54FDlrsy4HMcThxUbmcqy0Ou3bRjPR2f9A6QaNDNlolPhW1Z4gs+MTQOXJyAj2vdKwNKPwr8X6wyUtN4v8MiJt2yl4h3EVSVkGQIDAQAB
    types:
      - tree
  - peerId: 12D3KooWCUPYuMnQhu9yREJgQyjcz8zWY83rZGmDLwb9YR6QkbZX
    address:
      - 127.0.0.1:4432
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuOwKfzHLrm94jH4PElKfkB9geQ5OhtdbcS4K3TeyZ5xU0hi0TiXxOiHQOCg2uO7B/fnQcAArUBvPNa4QOvNuWRY+246FHYBxCJvJdfOpwirQbQ2l5iqR13rpSAELnF/zB4XMQa6wGVhsgWipvY9PUrLF6RwpeeBu9OtpVaA2oUiUXyD+v1f4dNXjZqrTKS9IycksGEEI4knEfG421K862BRty94pVWfqv/ZgpJUQZiWLX9CSbAdvjoHxOdm96VhMjTBw3oyv7hTr/zQR9y77OMFwOOBtn4QWXSS54r89inoksgGjH5cProhR+V4QZ4962TGsnc92j+IjtlxI/o3CuQIDAQAB
    types:
      - tree
  - peerId: 12D3KooWQxiZ5a7vcy4DTJa8Gy1eVUmwb5ojN4SrJC9Rjxzigw6C
    address:
      - 127.0.0.1:4730
    types:
      - file
  - peerId: 12D3KooWKLCajM89S8unbt3tgGbRLgmiWnFZT3adn9A5pQciBSLa
    address:
      - 127.0.0.1:4830
    encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0+QzaxFy+oVg3/NOakve7eRA90sjMsiUvQRdEx/ykDNku3n1ayfXaFSEVyZAXwf12Oght61hFisX46Oom6KMfztklZXb3suPxx5bTbss9iu/4+Y1bd1yELb/oBkApFTTl4xM8rLZ5mvCxJvH8r43OuCGaJuWNtnLEIAkIXwdDhvibcTlSw90d7MVDU5Z5nrUqDu6H2W2ifDtUFg0Ir3Q1zz/eysceeq9h0XnPl+t06JZDVCddWYd1P/iT6BRQTjxQaIbVa1xbGXfJ2k8M2RBGt5XWCoiKdRIO/+QYStBfW4EH13NjztyLilY7lnm7u+NJ8bah9+H/mqBE8Y+sSAVAwIDAQAB
    types:
      - coordinator
