id: 643d42c2c112117072700a8f
networkId: N9DU6hLkTAbvcpji3TCKPPd3UQWKGyzUxGmgJEyvhByqAjfD
nodes:
  - addresses:
      - stage1-any-sync-node1.anytype.io:443
    peerId: 12D3KooWN6Wwdod3axHpfWq1anBCgYG1sZK42RpgEZEokT4KnMu7
    types:
      - tree
  - addresses:
      - stage1-any-sync-node2.anytype.io:443
    peerId: 12D3KooWJuqyFQ2ZgnYFNhdHAddF7DrTPP2rNueLjw5BWDJa9kqg
    types:
      - tree
  - addresses:
      - stage1-any-sync-node3.anytype.io:443
    peerId: 12D3KooWCub3vY3kWmAQ5qf9TtKBHKY6Yk7F6tGb13M1sXqvcbV4
    types:
      - tree
  - addresses:
      - stage1-any-sync-node4.anytype.io:443
    peerId: 12D3KooWRzT7eeiqPpkaXabqrtLEi1WmWPoUqZVRYiguUdJQz3sz
    types:
      - tree
  - addresses:
      - stage1-any-sync-node5.anytype.io:443
    peerId: 12D3KooWPkZDAzAzioUmtd2HkPeFb8mrMgkkYtfL5Es69dbhoUMT
    types:
      - tree
  - addresses:
      - stage1-any-sync-node6.anytype.io:443
    peerId: 12D3KooWF5pVsv8oaPeZj7MeAXQAbdqqrGB7AEENMnxguZtEi44V
    types:
      - tree
  - addresses:
      - stage1-any-sync-node7.anytype.io:443
    peerId: 12D3KooW9xRUDQbW6bbsek45dQop9BDZBC8ATCpKxYssE8zMy2wa
    types:
      - tree
  - addresses:
      - stage1-any-sync-node8.anytype.io:443
    peerId: 12D3KooWBqUE5e6BuxWDiAAvYATq36qCUvNysyDMdddUqmeCb5jG
    types:
      - tree
  - addresses:
      - ec2-18-159-252-150.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWKcGtB8jsW7mpB8zWMdVrPTZygnwkRoUKBd2ETmRDFa8x
    types:
      - file
  - addresses:
      - ec2-3-68-113-221.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWR5ishjnaTfLbwQur6ifXSQDLSroaQxWH1KHmR1YL9Srk
    types:
      - file
  - addresses:
      - ec2-3-75-246-136.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWAzNCQWQSdfspUCT6ea3TLvJFahEHwXndh8PQGanjHhbF
    types:
      - file
  - addresses:
      - ec2-3-122-177-128.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWHyWNKYPdYeFK9eQ32UK9uqM1yTdXZT6qTTbtCowCYBAp
    types:
      - coordinator
  - addresses:
      - ec2-3-125-155-229.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWNPpzKPUzcf86KemKwa3ap8kBfCmPRWkBsvymGZdoBdni
    types:
      - coordinator
  - addresses:
      - ec2-3-65-13-48.eu-central-1.compute.amazonaws.com:443
    peerId: 12D3KooWB4hmEo7YAdWzAaFpjyk4npkcwrPm2kRigsWu3MP9Xdmg
    types:
      - coordinator

creationTime: 2023-04-17T14:59:46.807436097+02:00
