un:
  deadline: 15m
  timeout:  15m
  # didn't run linter on tests
  tests: false
  # don't check generated protobuf files
  skip-dirs:
    - pb/external_libs
    - pkg/lib/pb
  go: '1.18'

linters-settings:
  errcheck:
    check-blank: true
  errchkjson:
    report-no-exported: true
  gci:
    sections:
      - standard                       
      - default                       
      - prefix(github.com/anytypeio/go-anytype-middleware)
      - blank                          
      - dot                           
    skip-generated: false
    custom-order: true
  goimports:
    local-prefixes: github.com/anytypeio/go-anytype-middleware
  govet:
    check-shadowing: true
  funlen:
    lines: 120
    statements: 100
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    - dupl
    - gci
    - gocritic
    - gofmt
    - goimports
    - gosec
    - interfacebloat
    - importas
    - lll
    - misspell
    - nestif
    - prealloc
    - revive
    - unused
    - errcheck
    - funlen
    - gosimple
    - govet
    - typecheck
    - unconvert
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  rules:
      - severity: warning
        linters:
          - lll
