dir: "{{.InterfaceDir}}/mock_{{.PackageName}}"
testonly: True
with-expecter: True
all: False
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/anyproto/anytype-heart/space/typeprovider:
    interfaces:
      SmartBlockTypeProvider:
  github.com/anyproto/anytype-heart/core/wallet:
    interfaces:
      Wallet:
  github.com/anyproto/anytype-heart/core/event:
    interfaces:
      Sender:
  github.com/anyproto/anytype-heart/core/block/getblock:
    interfaces:
      Picker:
  github.com/anyproto/anytype-heart/pkg/lib/core:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/block/import/converter:
    interfaces:
      Converter:
  github.com/anyproto/anytype-heart/pkg/lib/database:
    interfaces:
      ObjectStore:
        config:
          dir: "{{.InterfaceDir}}"
          outpkg: "{{.PackageName}}"
          inpackage: true
  github.com/anyproto/anytype-heart/pkg/lib/localstore/objectstore:
    interfaces:
      ObjectStore:
  github.com/anyproto/anytype-heart/core/block/restriction:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/system_object:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/filestorage/filesync:
    interfaces:
      FileSync:
  github.com/anyproto/anytype-heart/space:
    interfaces:
      Service:
  github.com/anyproto/anytype-heart/core/subscription:
    interfaces:
      CollectionService:
