version: "3.9"

services:
  test:
    environment:
      - ANYTYPE_OFFLINE=true
    build: .
    volumes:
      - type: bind
        source: ./tests/.cache/anytype
        target: /var/anytype
    ports:
      - "${ANYTYPE_TEST_GRPC_PORT:?}:31007"
