version: "3"

services:
  test:
    container_name: test
    image: docker.pkg.github.com/anytypeio/python-anytype-testing/tests:latest
    volumes:
      - ./allure-results:/app/allure-results
    links:
      - middleware-node-a
      - middleware-node-b
    environment:
      TEST_MIDDLEWARE_NODE_A_ADDRESS_HOST: middleware-node-a
      TEST_MIDDLEWARE_NODE_A_ADDRESS_PORT: 31007
      TEST_MIDDLEWARE_NODE_A_ADDRESS_GATEWAY_PORT: 32007
      TEST_MIDDLEWARE_NODE_B_ADDRESS_HOST: middleware-node-b
      TEST_MIDDLEWARE_NODE_B_ADDRESS_PORT: 41007
      TEST_MIDDLEWARE_NODE_B_ADDRESS_GATEWAY_PORT: 42007
    command: bash -c "make test"

  middleware-node-a:
    stop_grace_period: 1s
    stop_signal: SIGABRT
    image: docker.pkg.github.com/anytypeio/go-anytype-middleware/server:${TAG}
    environment:
      ANYTYPE_GRPC_ADDR: "0.0.0.0:31007"
      ANYTYPE_LOG_LEVEL: "anytype-mw-app=DEBUG;grpc=DEBUG;anytype-gateway=DEBUG"
      ANYTYPE_LOG_NOGELF: 1
      ANYTYPE_GRPC_LOG: 3
      # local tracing
      #ANYTYPE_GRPC_TRACE: 3
      #JAEGER_AGENT_HOST: "docker.for.mac.localhost"
      #JAEGER_SERVICE_NAME: "mw-a"

  middleware-node-b:
    stop_grace_period: 1s
    stop_signal: SIGABRT
    image: docker.pkg.github.com/anytypeio/go-anytype-middleware/server:${TAG}
    environment:
      ANYTYPE_GRPC_ADDR: "0.0.0.0:41007"
      ANYTYPE_GATEWAY_ADDR: "0.0.0.0:42007"
      ANYTYPE_LOG_LEVEL: "anytype-mw-app=DEBUG;grpc=DEBUG;anytype-gateway=DEBUG"
      ANYTYPE_LOG_NOGELF: 1
      ANYTYPE_GRPC_LOG: 3
      # local tracing
      #ANYTYPE_GRPC_TRACE: 3
      #JAEGER_AGENT_HOST: "docker.for.mac.localhost"
      #JAEGER_SERVICE_NAME: "mw-b"
      #JAEGER_SERVICE_NAME: "mw-b"
