name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: test and build
      uses: cedrickring/golang-action/go1.14@1.5.2
      with:
        args: go build ./... && go test ./...
